# Config file for automatic testing at travis-ci.org
# This is an amazing project

dist: xenial

language: python

python:
  - "3.6"
  - "3.7"

env:
  - TOX_ENV=py3-django-111
  - TOX_ENV=py3-django-20
  - TOX_ENV=py3-django-21

matrix:
  fast_finish: true

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r requirements_test.txt

# command to run tests using coverage, e.g. python setup.py test
script: tox -e $TOX_ENV

after_success:
  - codecov -e TOX_ENV
